### ISSUE TITLE
Sub-folder does not getting read

### ISSUE THREAD

**Issue by reyou** [flesler/config-node#6]
var config2 = require('config-node')({
    ext: "js",
    dir: '\\config\\env', // where to look for files     
})();

I am getting error throw new Error('No file found for environment '+env);

Under function function extension(dir, env) {

In debug i see dir variable is:
""c:\myproject\server\config"

but should be;

"c:\myproject\server\config\env"

**Comment by flesler** [comment]
Hi,

I don't have much info honestly, I assume you're running this on Windows.

A few notes:
- Adding a `\` on a string in JavaScript escapes the next character, you need to add 2 slashes to actually insert a literal slash into a string.
- You don't need to start the dir with slash.
- You can use forward slashes even on Windows, Node.js path module handles that.

In short, try changing:
```js
'\config\env',
```

to:
```js
'config/env',
```

**Comment by flesler** [comment]
I assume that fixed the issue, reopen otherwise
